# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('category', models.CharField(choices=[('sales', 'SALE OF STOCK'), ('rent', 'RENT COLLECTION'), ('assets', 'SALE OF ASSETS'), ('tips', 'TIPS'), ('commisions', 'COMMISION')], max_length=15)),
                ('currency', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
